version: "2.2"
services:
 rabbitmq:
  image: "rabbitmq:3-management"
  networks:
    - rabbit_network
  ports:
    - "5672:5672"
    - "15672:15672"
  environment:
    - RABBITMQ_DEFAULT_USER=user
    - RABBITMQ_DEFAULT_PASS=pass
  volumes:
    - "rabbitmq_data:/data"
  healthcheck:
    test: [ "CMD", "rabbitmqctl", "status" ]
    interval: 5s
    timeout: 20s
    retries: 100

 client:
   build: ./client
   image: client
   networks:
     - rabbit_network
   depends_on:
     - rabbitmq
     - consumer
   restart: on-failure

 consumer:
   build: ./consumer
   image: consumer
   networks:
     - rabbit_network
   depends_on:
     - rabbitmq
   restart: on-failure

 handler:
   build: ./handler
   image: handler
   networks:
     - rabbit_network
   depends_on:
     - rabbitmq
   restart: on-failure

 writer:
   build: ./writer
   image: writer
   networks:
     - rabbit_network
   volumes:
     - .:/src/files
   depends_on:
     - rabbitmq
   restart: on-failure

networks:
  rabbit_network:
volumes:
  rabbitmq_data:
