[tool.poetry]
name = "user_story"
version = "0.1.0"
description = ""
authors = ["dvkuzmin <dk_187@mail.ru>"]

[tool.poetry.dependencies]
python = "^3.9"
pika = "^1.3.2"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
